
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook2;
	private global::Gtk.VBox vbox2;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Expander expDownloadAndConvert1;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label14;
	private global::Gtk.Entry edtDownloadLink;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label15;
	private global::Gtk.Entry edtFrom;
	private global::Gtk.Label label17;
	private global::Gtk.Entry edtTo;
	private global::Gtk.Label expDownloadAndConvert;
	private global::Gtk.Expander expConvertFromFiles;
	private global::Gtk.FileChooserWidget listSelectedFiles;
	private global::Gtk.Label GtkLabel13;
	private global::Gtk.Expander expHistoricalData;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VButtonBox vbuttonbox1;
	private global::Gtk.Button btnSelectAll;
	private global::Gtk.Button btnUnselectAll;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TreeView historicalStockListTreeview;
	private global::Gtk.VBox vbox5;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label12;
	private global::Gtk.Entry edtNumYears;
	private global::Gtk.CheckButton checkbutton1;
	private global::Gtk.Label GtkLabel11;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment8;
	private global::Gtk.VBox vbox6;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label16;
	private global::Gtk.Entry edtOutputDir;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label1;
	private global::Gtk.Entry edtDateFormat;
	private global::Gtk.Table table1;
	private global::Gtk.ComboBox combo1;
	private global::Gtk.ComboBox combo2;
	private global::Gtk.ComboBox combo3;
	private global::Gtk.ComboBox combo4;
	private global::Gtk.ComboBox combo5;
	private global::Gtk.ComboBox combo6;
	private global::Gtk.ComboBox combo7;
	private global::Gtk.ComboBox combo8;
	private global::Gtk.Label label6;
	private global::Gtk.Label GtkLabel17;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Label label7;
	private global::Gtk.Entry edtDelimiter;
	private global::Gtk.CheckButton chkIndexAsValue;
	private global::Gtk.HButtonBox hbuttonbox1;
	private global::Gtk.Button btnGiveIt;
	private global::Gtk.Button button2;
	private global::Gtk.Label labelStatus;
	private global::Gtk.Label label3;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.TextView textview1;
	private global::Gtk.Label label13;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Simple PSEGet");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 400;
		this.DefaultHeight = 500;
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		this.notebook2.ShowBorder = false;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.expDownloadAndConvert1 = new global::Gtk.Expander (null);
		this.expDownloadAndConvert1.CanFocus = true;
		this.expDownloadAndConvert1.Name = "expDownloadAndConvert1";
		// Container child expDownloadAndConvert1.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Download From ");
		this.hbox7.Add (this.label14);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label14]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.edtDownloadLink = new global::Gtk.Entry ();
		this.edtDownloadLink.CanFocus = true;
		this.edtDownloadLink.Name = "edtDownloadLink";
		this.edtDownloadLink.Text = global::Mono.Unix.Catalog.GetString ("http://www.pse.com.ph/html/Quotations/2011");
		this.edtDownloadLink.IsEditable = true;
		this.edtDownloadLink.InvisibleChar = '●';
		this.hbox7.Add (this.edtDownloadLink);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.edtDownloadLink]));
		w2.Position = 1;
		this.vbox3.Add (this.hbox7);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("From");
		this.hbox3.Add (this.label15);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label15]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.edtFrom = new global::Gtk.Entry ();
		this.edtFrom.CanFocus = true;
		this.edtFrom.Name = "edtFrom";
		this.edtFrom.IsEditable = true;
		this.edtFrom.InvisibleChar = '●';
		this.hbox3.Add (this.edtFrom);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.edtFrom]));
		w5.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("To");
		this.hbox3.Add (this.label17);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label17]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.edtTo = new global::Gtk.Entry ();
		this.edtTo.CanFocus = true;
		this.edtTo.Name = "edtTo";
		this.edtTo.IsEditable = true;
		this.edtTo.InvisibleChar = '●';
		this.hbox3.Add (this.edtTo);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.edtTo]));
		w7.Position = 3;
		this.vbox3.Add (this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.expDownloadAndConvert1.Add (this.vbox3);
		this.expDownloadAndConvert = new global::Gtk.Label ();
		this.expDownloadAndConvert.Name = "expDownloadAndConvert";
		this.expDownloadAndConvert.LabelProp = global::Mono.Unix.Catalog.GetString ("Download And Convert");
		this.expDownloadAndConvert.UseUnderline = true;
		this.expDownloadAndConvert1.LabelWidget = this.expDownloadAndConvert;
		this.vbox1.Add (this.expDownloadAndConvert1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expDownloadAndConvert1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.expConvertFromFiles = new global::Gtk.Expander (null);
		this.expConvertFromFiles.CanFocus = true;
		this.expConvertFromFiles.Name = "expConvertFromFiles";
		this.expConvertFromFiles.Expanded = true;
		this.expConvertFromFiles.BorderWidth = ((uint)(3));
		// Container child expConvertFromFiles.Gtk.Container+ContainerChild
		this.listSelectedFiles = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(0)));
		this.listSelectedFiles.WidthRequest = 0;
		this.listSelectedFiles.HeightRequest = 300;
		this.listSelectedFiles.Name = "listSelectedFiles";
		this.listSelectedFiles.SelectMultiple = true;
		this.expConvertFromFiles.Add (this.listSelectedFiles);
		this.GtkLabel13 = new global::Gtk.Label ();
		this.GtkLabel13.Name = "GtkLabel13";
		this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("Convert From File(s)");
		this.GtkLabel13.UseUnderline = true;
		this.expConvertFromFiles.LabelWidget = this.GtkLabel13;
		this.vbox1.Add (this.expConvertFromFiles);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expConvertFromFiles]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.expHistoricalData = new global::Gtk.Expander (null);
		this.expHistoricalData.CanFocus = true;
		this.expHistoricalData.Name = "expHistoricalData";
		// Container child expHistoricalData.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox ();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnSelectAll = new global::Gtk.Button ();
		this.btnSelectAll.CanFocus = true;
		this.btnSelectAll.Name = "btnSelectAll";
		this.btnSelectAll.UseUnderline = true;
		this.btnSelectAll.Label = global::Mono.Unix.Catalog.GetString ("Select All");
		this.vbuttonbox1.Add (this.btnSelectAll);
		global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnSelectAll]));
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnUnselectAll = new global::Gtk.Button ();
		this.btnUnselectAll.CanFocus = true;
		this.btnUnselectAll.Name = "btnUnselectAll";
		this.btnUnselectAll.UseUnderline = true;
		this.btnUnselectAll.Label = global::Mono.Unix.Catalog.GetString ("Unselect All");
		this.vbuttonbox1.Add (this.btnUnselectAll);
		global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnUnselectAll]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.hbox1.Add (this.vbuttonbox1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbuttonbox1]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.historicalStockListTreeview = new global::Gtk.TreeView ();
		this.historicalStockListTreeview.WidthRequest = 200;
		this.historicalStockListTreeview.HeightRequest = 150;
		this.historicalStockListTreeview.CanFocus = true;
		this.historicalStockListTreeview.Name = "historicalStockListTreeview";
		this.GtkScrolledWindow2.Add (this.historicalStockListTreeview);
		this.hbox1.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow2]));
		w17.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Years ");
		this.hbox2.Add (this.label12);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label12]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.edtNumYears = new global::Gtk.Entry ();
		this.edtNumYears.WidthRequest = 20;
		this.edtNumYears.CanFocus = true;
		this.edtNumYears.Name = "edtNumYears";
		this.edtNumYears.Text = global::Mono.Unix.Catalog.GetString ("20");
		this.edtNumYears.IsEditable = true;
		this.edtNumYears.InvisibleChar = '●';
		this.hbox2.Add (this.edtNumYears);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.edtNumYears]));
		w19.Position = 1;
		this.vbox5.Add (this.hbox2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.checkbutton1 = new global::Gtk.CheckButton ();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Single File");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.vbox5.Add (this.checkbutton1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.checkbutton1]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.hbox1.Add (this.vbox5);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox5]));
		w22.Position = 2;
		this.expHistoricalData.Add (this.hbox1);
		this.GtkLabel11 = new global::Gtk.Label ();
		this.GtkLabel11.Name = "GtkLabel11";
		this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString ("Download Historical Data");
		this.GtkLabel11.UseUnderline = true;
		this.expHistoricalData.LabelWidget = this.GtkLabel11;
		this.vbox1.Add (this.expHistoricalData);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.expHistoricalData]));
		w24.Position = 2;
		w24.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
		this.frame1.LabelXalign = 0.5F;
		this.frame1.LabelYalign = 0F;
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment8.Name = "GtkAlignment8";
		this.GtkAlignment8.LeftPadding = ((uint)(12));
		// Container child GtkAlignment8.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Output Directory");
		this.hbox5.Add (this.label16);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label16]));
		w25.Position = 0;
		w25.Expand = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.edtOutputDir = new global::Gtk.Entry ();
		this.edtOutputDir.CanFocus = true;
		this.edtOutputDir.Name = "edtOutputDir";
		this.edtOutputDir.IsEditable = true;
		this.edtOutputDir.InvisibleChar = '●';
		this.hbox5.Add (this.edtOutputDir);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.edtOutputDir]));
		w26.Position = 1;
		this.vbox6.Add (this.hbox5);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Date Format");
		this.hbox6.Add (this.label1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label1]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.edtDateFormat = new global::Gtk.Entry ();
		this.edtDateFormat.CanFocus = true;
		this.edtDateFormat.Name = "edtDateFormat";
		this.edtDateFormat.Text = global::Mono.Unix.Catalog.GetString ("MM/DD/YYYY");
		this.edtDateFormat.IsEditable = true;
		this.edtDateFormat.InvisibleChar = '●';
		this.hbox6.Add (this.edtDateFormat);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.edtDateFormat]));
		w29.Position = 1;
		w29.Expand = false;
		this.vbox6.Add (this.hbox6);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(5)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.combo1 = global::Gtk.ComboBox.NewText ();
		this.combo1.AppendText (global::Mono.Unix.Catalog.GetString ("SYMBOL"));
		this.combo1.AppendText (global::Mono.Unix.Catalog.GetString ("DATE"));
		this.combo1.AppendText (global::Mono.Unix.Catalog.GetString ("OPEN"));
		this.combo1.AppendText (global::Mono.Unix.Catalog.GetString ("HIGH"));
		this.combo1.AppendText (global::Mono.Unix.Catalog.GetString ("LOW"));
		this.combo1.AppendText (global::Mono.Unix.Catalog.GetString ("CLOSE"));
		this.combo1.AppendText (global::Mono.Unix.Catalog.GetString ("VOLUME"));
		this.combo1.AppendText (global::Mono.Unix.Catalog.GetString ("NFB/S"));
		this.combo1.Name = "combo1";
		this.combo1.Active = 0;
		this.table1.Add (this.combo1);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.combo1]));
		w31.LeftAttach = ((uint)(1));
		w31.RightAttach = ((uint)(2));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combo2 = global::Gtk.ComboBox.NewText ();
		this.combo2.AppendText (global::Mono.Unix.Catalog.GetString ("SYMBOL"));
		this.combo2.AppendText (global::Mono.Unix.Catalog.GetString ("DATE"));
		this.combo2.AppendText (global::Mono.Unix.Catalog.GetString ("OPEN"));
		this.combo2.AppendText (global::Mono.Unix.Catalog.GetString ("HIGH"));
		this.combo2.AppendText (global::Mono.Unix.Catalog.GetString ("LOW"));
		this.combo2.AppendText (global::Mono.Unix.Catalog.GetString ("CLOSE"));
		this.combo2.AppendText (global::Mono.Unix.Catalog.GetString ("VOLUME"));
		this.combo2.AppendText (global::Mono.Unix.Catalog.GetString ("NFB/S"));
		this.combo2.Name = "combo2";
		this.combo2.Active = 1;
		this.table1.Add (this.combo2);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.combo2]));
		w32.LeftAttach = ((uint)(2));
		w32.RightAttach = ((uint)(3));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combo3 = global::Gtk.ComboBox.NewText ();
		this.combo3.AppendText (global::Mono.Unix.Catalog.GetString ("SYMBOL"));
		this.combo3.AppendText (global::Mono.Unix.Catalog.GetString ("DATE"));
		this.combo3.AppendText (global::Mono.Unix.Catalog.GetString ("OPEN"));
		this.combo3.AppendText (global::Mono.Unix.Catalog.GetString ("HIGH"));
		this.combo3.AppendText (global::Mono.Unix.Catalog.GetString ("LOW"));
		this.combo3.AppendText (global::Mono.Unix.Catalog.GetString ("CLOSE"));
		this.combo3.AppendText (global::Mono.Unix.Catalog.GetString ("VOLUME"));
		this.combo3.AppendText (global::Mono.Unix.Catalog.GetString ("NFB/S"));
		this.combo3.Name = "combo3";
		this.combo3.Active = 2;
		this.table1.Add (this.combo3);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.combo3]));
		w33.LeftAttach = ((uint)(3));
		w33.RightAttach = ((uint)(4));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combo4 = global::Gtk.ComboBox.NewText ();
		this.combo4.AppendText (global::Mono.Unix.Catalog.GetString ("SYMBOL"));
		this.combo4.AppendText (global::Mono.Unix.Catalog.GetString ("DATE"));
		this.combo4.AppendText (global::Mono.Unix.Catalog.GetString ("OPEN"));
		this.combo4.AppendText (global::Mono.Unix.Catalog.GetString ("HIGH"));
		this.combo4.AppendText (global::Mono.Unix.Catalog.GetString ("LOW"));
		this.combo4.AppendText (global::Mono.Unix.Catalog.GetString ("CLOSE"));
		this.combo4.AppendText (global::Mono.Unix.Catalog.GetString ("VOLUME"));
		this.combo4.AppendText (global::Mono.Unix.Catalog.GetString ("NFB/S"));
		this.combo4.Name = "combo4";
		this.combo4.Active = 3;
		this.table1.Add (this.combo4);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.combo4]));
		w34.LeftAttach = ((uint)(4));
		w34.RightAttach = ((uint)(5));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combo5 = global::Gtk.ComboBox.NewText ();
		this.combo5.AppendText (global::Mono.Unix.Catalog.GetString ("SYMBOL"));
		this.combo5.AppendText (global::Mono.Unix.Catalog.GetString ("DATE"));
		this.combo5.AppendText (global::Mono.Unix.Catalog.GetString ("OPEN"));
		this.combo5.AppendText (global::Mono.Unix.Catalog.GetString ("HIGH"));
		this.combo5.AppendText (global::Mono.Unix.Catalog.GetString ("LOW"));
		this.combo5.AppendText (global::Mono.Unix.Catalog.GetString ("CLOSE"));
		this.combo5.AppendText (global::Mono.Unix.Catalog.GetString ("VOLUME"));
		this.combo5.AppendText (global::Mono.Unix.Catalog.GetString ("NFB/S"));
		this.combo5.Name = "combo5";
		this.combo5.Active = 4;
		this.table1.Add (this.combo5);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.combo5]));
		w35.TopAttach = ((uint)(1));
		w35.BottomAttach = ((uint)(2));
		w35.LeftAttach = ((uint)(1));
		w35.RightAttach = ((uint)(2));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combo6 = global::Gtk.ComboBox.NewText ();
		this.combo6.AppendText (global::Mono.Unix.Catalog.GetString ("SYMBOL"));
		this.combo6.AppendText (global::Mono.Unix.Catalog.GetString ("DATE"));
		this.combo6.AppendText (global::Mono.Unix.Catalog.GetString ("OPEN"));
		this.combo6.AppendText (global::Mono.Unix.Catalog.GetString ("HIGH"));
		this.combo6.AppendText (global::Mono.Unix.Catalog.GetString ("LOW"));
		this.combo6.AppendText (global::Mono.Unix.Catalog.GetString ("CLOSE"));
		this.combo6.AppendText (global::Mono.Unix.Catalog.GetString ("VOLUME"));
		this.combo6.AppendText (global::Mono.Unix.Catalog.GetString ("NFB/S"));
		this.combo6.Name = "combo6";
		this.combo6.Active = 5;
		this.table1.Add (this.combo6);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.combo6]));
		w36.TopAttach = ((uint)(1));
		w36.BottomAttach = ((uint)(2));
		w36.LeftAttach = ((uint)(2));
		w36.RightAttach = ((uint)(3));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combo7 = global::Gtk.ComboBox.NewText ();
		this.combo7.AppendText (global::Mono.Unix.Catalog.GetString ("SYMBOL"));
		this.combo7.AppendText (global::Mono.Unix.Catalog.GetString ("DATE"));
		this.combo7.AppendText (global::Mono.Unix.Catalog.GetString ("OPEN"));
		this.combo7.AppendText (global::Mono.Unix.Catalog.GetString ("HIGH"));
		this.combo7.AppendText (global::Mono.Unix.Catalog.GetString ("LOW"));
		this.combo7.AppendText (global::Mono.Unix.Catalog.GetString ("CLOSE"));
		this.combo7.AppendText (global::Mono.Unix.Catalog.GetString ("VOLUME"));
		this.combo7.AppendText (global::Mono.Unix.Catalog.GetString ("NFB/S"));
		this.combo7.Name = "combo7";
		this.combo7.Active = 6;
		this.table1.Add (this.combo7);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1 [this.combo7]));
		w37.TopAttach = ((uint)(1));
		w37.BottomAttach = ((uint)(2));
		w37.LeftAttach = ((uint)(3));
		w37.RightAttach = ((uint)(4));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combo8 = global::Gtk.ComboBox.NewText ();
		this.combo8.AppendText (global::Mono.Unix.Catalog.GetString ("SYMBOL"));
		this.combo8.AppendText (global::Mono.Unix.Catalog.GetString ("DATE"));
		this.combo8.AppendText (global::Mono.Unix.Catalog.GetString ("OPEN"));
		this.combo8.AppendText (global::Mono.Unix.Catalog.GetString ("HIGH"));
		this.combo8.AppendText (global::Mono.Unix.Catalog.GetString ("LOW"));
		this.combo8.AppendText (global::Mono.Unix.Catalog.GetString ("CLOSE"));
		this.combo8.AppendText (global::Mono.Unix.Catalog.GetString ("VOLUME"));
		this.combo8.AppendText (global::Mono.Unix.Catalog.GetString ("NFB/S"));
		this.combo8.Name = "combo8";
		this.combo8.Active = 7;
		this.table1.Add (this.combo8);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1 [this.combo8]));
		w38.TopAttach = ((uint)(1));
		w38.BottomAttach = ((uint)(2));
		w38.LeftAttach = ((uint)(4));
		w38.RightAttach = ((uint)(5));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Format  ");
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox6.Add (this.table1);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.table1]));
		w40.Position = 2;
		w40.Expand = false;
		w40.Fill = false;
		this.GtkAlignment8.Add (this.vbox6);
		this.frame1.Add (this.GtkAlignment8);
		this.GtkLabel17 = new global::Gtk.Label ();
		this.GtkLabel17.WidthRequest = 114;
		this.GtkLabel17.HeightRequest = 240;
		this.GtkLabel17.Name = "GtkLabel17";
		this.GtkLabel17.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Output Settings</b>");
		this.GtkLabel17.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel17;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w43.Position = 3;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Xalign = 0F;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Delimiter\n");
		this.fixed2.Add (this.label7);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label7]));
		w44.X = 15;
		w44.Y = 10;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.edtDelimiter = new global::Gtk.Entry ();
		this.edtDelimiter.WidthRequest = 50;
		this.edtDelimiter.CanFocus = true;
		this.edtDelimiter.Name = "edtDelimiter";
		this.edtDelimiter.Text = global::Mono.Unix.Catalog.GetString (",");
		this.edtDelimiter.IsEditable = true;
		this.edtDelimiter.InvisibleChar = '●';
		this.fixed2.Add (this.edtDelimiter);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.edtDelimiter]));
		w45.X = 80;
		w45.Y = 7;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.chkIndexAsValue = new global::Gtk.CheckButton ();
		this.chkIndexAsValue.CanFocus = true;
		this.chkIndexAsValue.Name = "chkIndexAsValue";
		this.chkIndexAsValue.Label = global::Mono.Unix.Catalog.GetString ("Index Value as Volume");
		this.chkIndexAsValue.Active = true;
		this.chkIndexAsValue.DrawIndicator = true;
		this.chkIndexAsValue.UseUnderline = true;
		this.fixed2.Add (this.chkIndexAsValue);
		global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.chkIndexAsValue]));
		w46.X = 265;
		w46.Y = 7;
		this.vbox1.Add (this.fixed2);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed2]));
		w47.Position = 4;
		w47.Expand = false;
		w47.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		this.hbuttonbox1.Name = "hbuttonbox1";
		this.hbuttonbox1.BorderWidth = ((uint)(9));
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnGiveIt = new global::Gtk.Button ();
		this.btnGiveIt.CanFocus = true;
		this.btnGiveIt.Name = "btnGiveIt";
		this.btnGiveIt.UseUnderline = true;
		this.btnGiveIt.Label = global::Mono.Unix.Catalog.GetString ("Give it to me!");
		this.hbuttonbox1.Add (this.btnGiveIt);
		global::Gtk.ButtonBox.ButtonBoxChild w48 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnGiveIt]));
		w48.Expand = false;
		w48.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Goodbye");
		this.hbuttonbox1.Add (this.button2);
		global::Gtk.ButtonBox.ButtonBoxChild w49 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button2]));
		w49.Position = 1;
		w49.Expand = false;
		w49.Fill = false;
		this.vbox1.Add (this.hbuttonbox1);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
		w50.Position = 5;
		w50.Expand = false;
		w50.Fill = false;
		this.vbox2.Add (this.vbox1);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox1]));
		w51.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.labelStatus = new global::Gtk.Label ();
		this.labelStatus.Name = "labelStatus";
		this.labelStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.vbox2.Add (this.labelStatus);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelStatus]));
		w52.Position = 1;
		w52.Expand = false;
		w52.Fill = false;
		this.notebook2.Add (this.vbox2);
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Converter");
		this.notebook2.SetTabLabel (this.vbox2, this.label3);
		this.label3.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow3.Add (this.textview1);
		this.notebook2.Add (this.GtkScrolledWindow3);
		global::Gtk.Notebook.NotebookChild w55 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.GtkScrolledWindow3]));
		w55.Position = 1;
		// Notebook tab
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("About");
		this.notebook2.SetTabLabel (this.GtkScrolledWindow3, this.label13);
		this.label13.ShowAll ();
		this.Add (this.notebook2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.expDownloadAndConvert1.Hide ();
		this.expHistoricalData.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.notebook2.ChangeCurrentPage += new global::Gtk.ChangeCurrentPageHandler (this.notebook_ChangeCurrentPage);
		this.expDownloadAndConvert1.Activated += new global::System.EventHandler (this.OnExpDownloadAndConvert1Activated);
		this.expConvertFromFiles.Activated += new global::System.EventHandler (this.OnExpDownloadAndConvert1Activated);
		this.expHistoricalData.Activated += new global::System.EventHandler (this.OnExpDownloadAndConvert1Activated);
		this.btnSelectAll.Clicked += new global::System.EventHandler (this.btnSelectAll_Click);
		this.btnUnselectAll.Clicked += new global::System.EventHandler (this.btnUnselectAll_Click);
		this.btnGiveIt.Clicked += new global::System.EventHandler (this.OnBtnGiveItClicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
