DROP TABLE MISCTAB;
CREATE TABLE MISCTAB (
	MISCKEY	INTEGER PRIMARY KEY,
	TRADEDATE TEXT NOT NULL,
	ADVANCE INTEGER,
	DECLINE INTEGER,
	UNCHANGED INTEGER,
	TRADEDISSUES INTEGER,
	NUMTRADES INTEGER,
	FOREIGNBUY NUMERIC(18),
	FOREIGNSELL NUMERIC(18),
	CROSSVOLUME INTEGER,
	CROSSVALUE INTEGER,
	BLOCKSALES TEXT
);

DROP TABLE TRADETAB;
CREATE TABLE TRADETAB (
	TRADEKEY INTEGER PRIMARY KEY,
	TRADEDATE TEXT NOT NULL,
	SYMBOL TEXT(10) NOT NULL,
	OPEN NUMERIC(14,5),
	HIGH NUMERIC(14,5),
	LOW NUMERIC(14,5),
	CLOSE NUMERIC(14,5),
	VOLUME NUMERIC(18),
	VALUE NUMERIC(18,5),
	NETFOREIGNBUY NUMERIC(18),
	MKTPERCENT NUMERIC(12,5),
	SECTORID INTEGER
);

DROP INDEX XUQ_MISCTAB_DATE;
CREATE UNIQUE INDEX XUQ_MISCTAB_DATE ON MISCTAB (TRADEDATE);


DROP INDEX XUQ_TRADETAB_DATE;
CREATE UNIQUE INDEX XUQ_TRADETAB_DATE ON TRADETAB(TRADEDATE, SYMBOL);

DROP TRIGGER DELETE_MISC;
CREATE TRIGGER DELETE_MISC 
	AFTER DELETE ON TRADETAB 
BEGIN 
	DELETE FROM MISCTAB WHERE TRADEDATE = OLD.TRADEDATE;
END;


CREATE TABLE SECTORS (
	SECTORID INTEGER NOT NULL PRIMARY KEY,
	SYMBOL TEXT(10) NOT NULL	
);

CREATE TABLE STOCKS (
	SYMBOL TEXT(10) NOT NULL PRIMARY KEY,
	DESCRIPTION TEXT
);